version: "2.13"

services:
  node1:
    build: .
    image: flockbrain
    container_name: Node1
    environment:
      ID: 1
      ADDRESS: Node1:10000
      ADDRESS2: Node2:10001
      ADDRESS3: Node3:10002
      GENESIS: 0

  node3:
    build: .
    image: flockbrain
    container_name: Node3
    environment:
      ID: 3
      ADDRESS: Node3:10002
      ADDRESS2: Node1:10000
      ADDRESS3: Node2:10001
      GENESIS: 0

  node2:
    build: .
    image: flockbrain
    container_name: Node2
    environment:
      ID: 2
      ADDRESS: Node2:10001
      ADDRESS2: Node1:10000
      ADDRESS3: Node3:10002
      GENESIS: 1
    depends_on:
      - node1
      - node3